language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install -r ./requirements.txt
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
- molecule --debug test
after_script:
- molecule --debug destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: e4JUhLosio6Ls3HX4eELZ4ghJai2kAKl8mxQbuylTIhXW2+MUB3UD8ONRcvadJYZZb7KMRZnEF7Rg81PamstEJu2lCL7j3JiIgzXqoaZVIdwKKUm2gPgyDL2ra+3nYlEkG+dx/GyBov8clIFvQYzFCBRNKrSeTbHYeSpvG3Q4Hou/cAIR2tIx+/ONKlSff/RMIjk68ZKZraOw8a9Lj8EUTP2hbPIlNUeXqiLCrqUv+xZ+NyK0/0ce5K6gkyhoAFDaX2ZhJKFbqNWcjgohPBagEDE4r2bIanHLvjyQkYQNn/ndZ6k9hv2rplJhG7trTqj6Cck5LMq/FslUpkbjR09GTNR/DZOiK5pg5OcGZGi4DS1HMmKoTyml+LaxoHjlqjg4P+ePT0SVlmI3d1YdniXRqJfo82JEoGNqmctz45SZapeuq32mfTiSExAMRB+2FgbavV2OR1+J3K+Fgkm0Q5qDVQ6a5L2CJhWzyMS1TviQZbiHcth9Yp8GpbelwnXfsieXQZhxIoc1rOG+V1FDolYKoLnh9ObrD+mjheX35xCV6ACQSTUhShshlqv2avwXAxxSYBU45CHlIeT1fnFZleAKSLX2USFygbMDK/lyIhJqMnAeh94BZFTCsSLd/gp7S/YsTXJToMNL3r7Srs++pr4FTx2s3/qnVInF8mfcmI+64M=
  - secure: lOJkEUCn9Mrc2CGHNGW4taPGHgNOHyhAuukpdWt6oX4i1b8S+Q4noFRGD7psMzYc1gHqmZWgcJpxiqz2SiM+TJ/xmVB74KIcon9p8nr2Ig21skl8oJWLy322tYxG70wYwmdz1Bsnzge6xLWZwvs4EGjEwuamzS0xeDM8gBP1DoHIn8bvy3EbIz0riAuOIqLqyaDN3Viu/Ii7TxXkcidHoeeKvrXsIwZXoEk6CtV9CV0PfackLWXOSSI2Ch3N9tg+RaQqlbN/GOYad/tXo9Nz11qum3UID/VW4dts6yQZi9uRIEbBcMosZZ7Qf/KAxc3PDgGrismisCpQgbHp4v2oWzXuE82gsRWxYqojQPPmgJCFku0SogD1PHfVIe3pvIcGo91kdKX8ONlK7NaMhVZvvf134Dijs9vi3UEQcAUkKOpJJiqwshVZ83UWB0+HQDRqsOqj5QVByij1EiyMk0gVlJsTkdFSeEyKJqPVKruujuGQWT0D2GyuxoiYy7+g+jyIvNtErl0JaiE9mCf2fx5hKuSj0HOm/L4IBFtCfE0mCPabz9FFeZ3t3+vagf+UiRIkH1Q3kWu6eUm5COsTvGxMI7zm8tRsrJl7RSt4xs6l0y6ux+Wiu7zvYDOMO1vrGr/wJ+gVMvzGOx151bcXD546bknacb9dZaOp0MpX1RRorWk=
  - secure: SS5iJ0VoTKe+uvBTH+OXlEUyM0AsQsjTmH/Su41YPTbr4mITsJsJolueGBBBO3lXNfy6LhppYFSIykTnoQRzFghdblzmy4om93vDZlmjo15quzLcX0yjSmv4+WLACctxD/B2s4qqkb3vqWs37bq1JYNTl8SE1b1AxLg9gWoyIGjKZX3MGtHiH1MvDFQqeohZmSY2d8qQDgP5ZlVw4fSfUt5RhiN5Rv09LZF9DYNMoDGqm+yRPrXLG9nMkuw8mRNKSSnS9aypFmjpwhjfCBlvJlDg1IA0c/4WMFiPVaQmIq6DP580cqUoBbksQJVg2C9kNpwM5yohPEjHWim0IA752p65tEnqq+aQdr1paDoJoqkdwgw03CVihe6H+jpt4ka3jWVgOeIfudnNONUnIBgeSu3HPfCIJa6y49N1iwC1g+mjlEQS8NtRY+rgXnq9tNGr+ssT1EBu3IZTtG4NaeyoZnOiQQ/vxp9ncricIE9uR3X3PDs+O5zjjQfOMZR1JggYuZAfBy/j2uVSfCzz/Ipfnk/NUq8S7iH007RN3jYxSrGGftA4gep4X8fmpkk1WS7n2vMBQVuJwV6a8vPTkey0V3O4RK/P0rwbNjdC5xrDS0TpVv+sArS31WsZQ4qD9YTBAVw3J1q0rF94GjoC25iBFJUf4T7HUzFslqE0v3szA7E=
notifications:
  slack:
    rooms:
      - secure: sxLtIwo9iA2T6s2eEICFeZoGg75Z5M0LTRfHY2/M73vER5wxZQUFHoe8/nosjNfhB52Zx9n2oW5wzPJRkcp0xa781kbsinvef/bUf2/z8T1DpG0WrJfS04P4kH06TBzmjMG3v0Qv+t7p5pVFV8OwLLSi4fGksxU8RO72POiFpivt4vwIOho/CsDVKhA6Ui0ImuFKKaBfKQRHjAQ/hZtUHhL/Cmih+fpHsgdAHHE3HRGo1m6dO8gA7ecqamHxpy1njvQiQbAqSW4u+z8Fj404+ayNOnF0tHe/U81gFW56wMUvS92FD+F8aIL6dqphZDpWrMxgahx2P0RshWcm3v7bvnat2M9ZRIwJ98A2kZvG/RB+w0t4lUcY08nrLXtNrdUViIeohmSsoEaDocsDE/0Fgs+A7uPPYHwzFrtRL8frIMtuBE0T2Ip0OeVaoUhf+O5IUrgR2JXRm1B7j8TBheEtdl3uUuQ0ogaXd6f80399Xr/HwvwPiRJ4zLbWNew3tqZzpnDcPf/VkNm9PpJYNNO6vidDjPEIDOOlwygyLmCL2CIhqx/oy5WvRtIZpv2NfO7eISxVUtbRAymw9KGW5GD8ZiTndurt339CMHG1elV5Z7+9oSD/94ptQEZluDsxN/GTQOeyGC8EI9QLAkZEFi/Lc8xGudHqht5K1r/f3SymyF0=
